### ISSUE TITLE
Users crashing while in a Dreamlands biome, unable to log back in.   Had to disable the mod to allow logon again.

### ISSUE THREAD

**Issue by pokemongojsb1** [dragoni7/Dreamland-1.19.2#2]
Forge 43.1.3
Game 1.19.2
Dreamland-forge-1.19.2-1.1.4.jar mod installed Server and Client side

CrashReport.TXT attached, from the server log.   Hopefully it'll help identify what may have happened.

Have had several users complain that they crash and then cannot rejoin after the crash.   The crash just tells them a generic error.  So, looking at the server crash logs, I found a log that mentioned DreamLand mod.    Removing the mod, it allowed everyone to log back on.      It ruined the loaded chunks that were missing your mod, flooding the server with "missing object" errors, but at least they got back in.    

Hopefully the log I attached makes more sense to you than it does to me :)

**Comment by pokemongojsb1** [comment]
https://pastebin.com/hi0WGn3Q

Just in case the attached log doesn't show up, here's a pastebin of the log as well.

**Comment by dragoni7** [comment]
Thank you for bringing this to my attention. The crash was caused by any entity stepping in the tar liquid, in this case, a skeleton. The bug was easy to fix, but unfortunately I am in the middle of a major content addition so the fix will have to be included in the next update. About a week or two.
