### ISSUE TITLE
[1.19.2-1.2.0.5] Endermen holding a Dreamland block crashes

### ISSUE THREAD

**Issue by TelepathicGrunt** [dragoni7/Dreamland-1.19.2#7]
Got a strange crash where it seems an Enderman is holding a Dreamland block that has a tint index based on biomes. I was in the Toxic Jungle in this case so one of those blocks are a likely candidate. Since the Enderman is holding the block, it most likely means the blockpos being passed into the color lambda is null and Dreamland is crashing on that null blockpos

 
Stacktrace: https://paste.ee/p/hl9oN

**Comment by dragoni7** [comment]
Hello, I attempted to fix this by removing the block from the enderman_holdable tag and from my testing it seemed to prevent them from picking up the block. Though that was just a bandaid fix and I assume it didn't work since you got this error still. I will continue to dig at this, so thanks for bringing this up! I am still figuring out what is wrong with my block color registration code
